name: Lint Check

# This workflow runs ESLint on pull requests to the main or develop branches.
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      # Download the code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Install pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      # Sets Node.js 22
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      # 4. Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 5. Run the lint script (the one at the package.json)
      - name: Run ESLint
        run: pnpm run lint